apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  selector:
    matchLabels:
      app: golang
  replicas: 1
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: nginx:1.14.2
        ports:
        - containerPort: 8080